export const womenInCS = [
  { firstName: "Barbara", lastName: "Liskov", summary: "One of the first women in the US to obtain a PhD in computer science; now a computer scientist at MIT." },
  { firstName: "Ada", lastName: "Lovelace (Countess of Lovelace)", summary: "A British mathematician and writer, she is often regarded as the first computer programmer." },
  { firstName: "Grace", lastName: "Hopper", summary: "A computer scientist and naval officer who developed the first compiler for computer programming language." },
  { firstName: "Ida", lastName: "Rhodes", summary: "A mathematician and computer pioneer who worked on the development of the first electronic computer, ENIAC." },
  { firstName: "Adele", lastName: "Goldberg", summary: "An American computer scientist who made significant contributions to the design of the Smalltalk programming language and the development of object-oriented programming." },
  { firstName: "Lynn", lastName: "Conway", summary: "An American computer scientist and electrical engineer who made groundbreaking contributions to VLSI (Very Large Scale Integration) design and teaching." },
  { firstName: "Hedy", lastName: "Lamarr", summary: "Perhaps best known as a glamorous Hollywood actress, Hedy Lamarr was also an inventor. She developed a radio guidance system for Allied torpedoes during World War II, a technology that became a basis for modern Wi-Fi, Bluetooth, and GPS communication." },
  { firstName: "Radia", lastName: "Perlman", summary: "An American software designer and network engineer, often referred to as the \"Mother of the Internet.\" She designed the Spanning-Tree Protocol (STP), which is fundamental to the operation of network bridges." },
  { firstName: "Joan", lastName: "Clarke", summary: "A British code-breaker during World War II, who worked alongside Alan Turing at Bletchley Park. She played a crucial role in breaking the German Enigma machine ciphers." },
  { firstName: "Katherine", lastName: "Johnson", summary: "An African-American mathematician who made critical calculations for NASA's space missions, including those of the Mercury and Apollo programs. Her work was pivotal in the early success of the US space program." },
  { firstName: "Sophie", lastName: "Wilson", summary: "A British computer scientist and software engineer, she designed the instruction set for the BBC Micro and was heavily involved in the ARM processor design." },
  { firstName: "Mary Lou", lastName: "Jepsen", summary: "An American engineer and businesswoman who has made innovations in display technology and co-founded companies like One Laptop per Child and Pixel Qi." },
  { firstName: "Annie", lastName: "Easley", summary: "An African-American computer scientist, mathematician, and rocket scientist. She worked for the Lewis Research Center of NASA and made significant contributions to space exploration and technology." },
  { firstName: "Fei-Fei", lastName: "Li", summary: "Co-creator of ImageNet and Professor of Computer Science at Stanford University." },
  { firstName: "Shafi", lastName: "Goldwasser", summary: "A computer scientist and mathematician known for her work in cryptography and complexity theory. She is a recipient of the Turing Award, often referred to as the \"Nobel Prize of Computing.\"" },
  { firstName: "Karen", lastName: "Spärck Jones", summary: "A British computer scientist who made significant contributions to natural language processing and information retrieval. She is best known for her work on inverse document frequency (IDF) in information retrieval, which is still widely used today." },
  { firstName: "Marie", lastName: "Curie", summary: "A Polish-born physicist and chemist, Marie Curie is famous for her pioneering research on radioactivity. She was one of the first women to win a Nobel Prize, and her work laid the foundation for future developments in X-ray technology and cancer treatment." }
]